---
- name: debian | Installing KVM
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: "{{ kvm_debian_packages }}"
    state: present
  register: result
  until: result is successful

- name: debian | Installing Additional Ubuntu Packages
  become: true
  ansible.builtin.apt:
    name: "ubuntu-vm-builder"
    state: present
  register: result
  until: result is successful
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version < "18.10"
