---
# handlers file for ansible-kvm
- name: restart libvirt-bin
  service:
    name: "libvirt-bin"
    state: "restarted"
    enabled: true
  become: true
  when: not ansible_check_mode

- name: restart libvirtd
  service:
    name: "libvirtd"
    state: "restarted"
    enabled: true
  become: true
  when: not ansible_check_mode

- name: restart ssh
  service:
    name: "ssh"
    state: "restarted"
  become: true
  when: 
    - not ansible_check_mode 
    - ansible_os_family == "Debian"
    
 - name: restart ssh
  service:
    name: "sshd"
    state: "restarted"
  become: true
  when: 
    - not ansible_check_mode 
    - ansible_os_family == "RedHat"
